app:
  services:
    client-service: http://client-service:8080
    application-service: http://application-service:8082

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%t] %logger{36} : %m%n"
