server:
  port: 8088

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://127.0.0.1:8888
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - http://localhost:5173
                  - http://localhost:3000
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
          routes:
            - id: smoke-health
              uri: forward:/actuator/health
              predicates:
                - Path=/api/smoke
            - id: client-service
              uri: ${app.services.client-service}
              predicates:
                - Path=/api/v1/clients/**,/api/v1/external-requests/**,/api/v1/batch-requests/**
              filters:
                - StripPrefix=2
            - id: application-service
              uri: ${app.services.application-service}
              predicates:
                - Path=/product/**,/service/**,/profile-change/**,/document/**,/claim/**,/authority/**,/general-check,/applications/**
              metadata:
                response-timeout: 600000

app:
  services:
    client-service: http://127.0.0.1:8080
    application-service: http://127.0.0.1:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
